server:
    port: 8080
    mode: debug
mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: test
    timeout: 10s
    maxConn: 100
    maxIdleConn: 10
redis:
    host: 127.0.0.1
    port: 6379
    db: 0
