// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"template/internal/data"
	"template/internal/handler"
	"template/internal/router"
	"template/internal/server/http"
	"template/internal/service"
	"template/pkg/app"
	"template/pkg/config"
	"template/pkg/log"
)

// Injectors from wire.go:

func wireApp(configConfig *config.Config, logger log.Logger) (*app.App, func(), error) {
	engine := http.NewEngine(configConfig, logger)
	wsRouter := router.NewWsRouter(engine, logger)
	dataData, cleanup, err := data.NewData(logger, configConfig)
	if err != nil {
		return nil, nil, err
	}
	testRepo := data.NewTestRepo(dataData, logger)
	testService := service.NewTestService(testRepo)
	testHandler := handler.NewTestHandler(testService, logger)
	httpRouter := router.NewHttpRouter(engine, testHandler)
	server := http.NewServer(configConfig, engine, wsRouter, httpRouter)
	appApp := newApp(logger, server)
	return appApp, func() {
		cleanup()
	}, nil
}
